### ISSUE TITLE
`responsive.lock` mixin doesn't work on the HTML element if you use use a global font size other than 16px

### ISSUE THREAD

**Issue by portfolioris** [supple-kit/supple-css#32]
**Describe The Bug:**
The `responsive.lock` utility and `typography.font-size` don't play nicely together, if you use a global font size other than 16px. Fonts get big if default font-size is set really low.

**To Reproduce:**
Add
```
@use 'node_modules/@supple-kit/supple-css/settings/defaults' with (
  $font-size: 12px,
}

html {
  font-size: responsive.lock(vars.$font-size, vars.$font-size + 4px, desk, tv);
}

.some-element {
  @include typography.font-size(vars.$milli);
}
```

**Expected behavior:**
It all scales proportionally.

**Environment:**
MacOS

* **Supple CSS Version**: 5.1.0
* **Node.js Version**: 16.13.1
* **NPM Version**: 8.1.2
* **Browser**: Firefox

**Comment by bramsmulders** [comment]
This is solved by #33, will be released shortly 👍🏼
