### ISSUE TITLE
Default $mq-breakpoints setting can't be overwritten

### ISSUE THREAD

**Issue by ghost** [supple-kit/supple-css#6]
https://github.com/supple-css/supple/blob/82d5829b6863715e0dd2cade0a94e0fca52f9f41/lib/settings/_responsive.scss#L16
Should contain `!default;`: this variable can't be overwritten from vars - which is included first in the entry.

**Comment by portfolioris** [comment]
Fixed in PR https://github.com/supple-css/supple/pull/7

**Comment by bramsmulders** [comment]
Merged into develop & scheduled for next minor release
